name: flutter_project_acme
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  keyboard_actions:
    git:
      url: https://github.com/mateusfsilva/flutter_keyboard_actions.git
      ref: e70f30c95fa5879d22266f829a26f24893dccee2
  cupertino_icons: ^1.0.2
  # Localization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.2.2
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  test: ^1.21.1

  lint: ^1.8.2
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fruits/
    - assets/iconAlert/
  
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
 
